### ISSUE TITLE
XUEETComunnicator constructor

### ISSUE THREAD

**Issue by glararan** [charlieMonroe/SwiftEET#2]
Ahoj,

Snažím se udělat appsku na ios pro párování s tiskárnou z číny, ale ať koukám jak koukám, nemůžu ve zdrojáku najít konstruktor s argumentem "account", který používáš v readme.
`let communicator = try XUEETCommunicator(account: self.account)`

Dále mohl bych se zeptat jakou formou includuješ XUCore?

Díky

**Comment by charlieMonroe** [comment]
Ahoj,

`init(account:)` v Readme je jen nejaky `convenience` initializer, ktery mam ve svem projektu - `account` ma pod sebou `XUCzechLocaleSpecificPreferencesData` a DIC. Mel bych to Readme asi oeditovat... Kazdopadne vytvorit `XUCzechLocaleSpecificPreferencesData` a zavolat `init(localeSpecificData:vatRegistrationID:)`.

`XUCore` includuju jako git submodule a v Xcode jako subproject.

**Comment by glararan** [comment]
Díky, ještě prosímtě snad poslední dotaz, XMLElement máš z nějakého opensource modulu? Koukám, že je součástí Foundation, ale ať ho mám importnutý jak chci, stejně mi to píše, že XMLElement neexistuje :/

**Comment by charlieMonroe** [comment]
Ja to pouzivam na macOS, kde je XMLDocument, XMLElement, atd. Na iOS z mne neznamych duvodu tyto XML wrappery nejsou. Da se to resit napr. pres KissXML (https://github.com/robbiehanson/KissXML). Bohuzel tam tusim neni par veci doimplementovanych pro plnou kompatibilitu, ale da se to jednoduchymi zmenami predelat. Budu vdecny za pripadny iOS-kompatibilni pull-request.

**Comment by glararan** [comment]
Můžu poprosit o založení branche iOS? Mám to hotové, ale je tam docela dost změn, využívá to 2 knihovny na XML (jedna umí číst, druhá psát, co se dá dělat) a 1 na podpis, ani iOS neumí podepsat sám tržbu :/

**Comment by charlieMonroe** [comment]
Urcite:

https://github.com/charlieMonroe/SwiftEET/tree/ios

Kazdopadne do budoucna bych rad udelal nejaky ekvivalent toho KissXML v ramci XUCore, jen jsem k tomu zatim nemel dostatecnou motivaci/cas. To bych pak kdyztak predelal a dal pryc ty dve externi zavislosti.

**Comment by glararan** [comment]
Mohl bych poprosit o write access? jsem trošku nováček na macu a gitkraken neumí pull request ze stejné branche :/

**Comment by charlieMonroe** [comment]
S Pull Requesty by to melo fungovat takto:

- udelat fork u sebe na GH
- commitnout na svuj fork
- vytvorit pull request zpet do tohoto repo. Vse lze udelat z GH na webu. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by glararan** [comment]
super díky, vytvořeno :) akorát mám trošku svůj codestyle tak se omlouvám, kdyžtak si to přeformátuj :)

**Comment by charlieMonroe** [comment]
Muzes posim udelat novy commit, kde jsou taby misto spacu? Takhle nevim, co se tam presne zmenilo, protoze jsou v diffu vsechny radky... :-/

Jinak doporucuji pouzivat Swift code style guidelines, minimalne nedavat { na separatni radek.

Diky.

**Comment by glararan** [comment]
Používám taby, ale Xcode je asi nahrazuje mezerama, ve VS to jde nastavit. V nastavení jsem se popravdě nehrabal, abych koukal jestli to spacuje nebo tabuje. Nj já mám spíš zajetý C++ code style, to je tak když člověk jde psát jiným jazykem :/ právě nemám rád, když není { na sep. řádku. Vím, že je v tom bordel protože každý píše jinak, pro mě je to přehledné takto, pro tebe byl původní. Ideální by bylo si to stáhnout a předělat codestyle podle sebe :)

**Comment by charlieMonroe** [comment]
Codestyle si predelam, jen prosim ty taby, abych se podival, co se zmenilo:

- v Xcode Preferences > Text Editing > Indentation > Prefer Indenting Using > Tabs
- pak v souboru vybrat text a v menu Editor > Structure > Re-Indent

Diky!

**Comment by charlieMonroe** [comment]
Nezlob se, ale proc jsi predelaval vsude slozeny zavorky na separatni radky? Tohle rozhodne nemuzu k sobe pustit - to je uplne C# kod.

BTW do budoucna doporucuji resit veskery rozdily direktivama:

```
#if os(iOS)
    import KissXML
    typealias XUXMLElement = DDXMLElement
#else
    typealias XUXMLElement = XMLElement
#endif



...
```

Pak se tam nemusi skoro nic menit...
